name: dl-workshop
channels:
- conda-forge
dependencies:
- python>=3.7
- black>=20.8b1
- conda
- ipywidgets>=7.6.3
- jax>=0.2.8
- jaxlib>=0.1.59
- jupyter
- jupyterlab>=3.0.5
- mamba
- matplotlib>=3.3.3
- mkdocs>=1.1.2
- mkdocs-material>=6.2.5
- mkdocs-material-extensions>=1.0.1
- nodejs>=15.3.0
- numpy>=1.19.5
- pip
- pydocstyle>=5.1.1
- pyjanitor>=0.20.10
- pyprojroot>=0.2.0
- pyyaml>=5.4.1
- scikit-learn>=0.24.1
- scipy>=1.6.0
- seaborn>=0.11.1
- tqdm>=4.56.0
- pip:
  - mknotebooks>=0.6.1
  - celluloid>=0.2.0
