name: dl-workshop
channels:
- defaults
- conda-forge
- ericmjl
dependencies:
- python=3.7
- jupyter
- jupyterlab
- conda
- scikit-learn
- numpy
- scipy
- matplotlib
- seaborn
- nodejs
- ipywidgets
- pyyaml
- pyjanitor
- tqdm
